### PR TITLE
Experiment restructure

### PR DESCRIPTION
**Pull request by raphaelschwinger**
This PR restructures our experimental setting in the following way:
- folder structure: 
	```
	experiments/biofoundation/
			- birdset
				- fewshot
					- fewshot_config
					- beats
					- ....	 	
				- finetuning
				- linearprobing
			- beans
				- fewshot
				- finetuning
				- linearprobing
	```
- `class BirdSetModel(nn.Module)` defines model parameters
	- adds a `freeze_backbone` parameter e.g. for linearprobing settings
	- a classifier parameter to make the classifier configurable through hydra
- moves `k_samples` to `BaseDatamodule._fewshot_preprocess`
- update README to include best results :)

### CODE REVIEW

**Comment by raphaelschwinger** [comment]
@PariaValizadeh @XgamerTV 
What do you think?

**Comment by PariaValizadeh** [comment]
> probi

It sounds good to me.

**Comment by PariaValizadeh** [comment]
> @PariaValizadeh @XgamerTV What do you think?

It sounds good to me

**Comment by The-Mats** [comment]
> @PariaValizadeh @XgamerTV 
> 
> What do you think?

Yeah sounds good 👍🏻

**Pull request merged**
